### ISSUE TITLE
community/themes crashes the app

### ISSUE THREAD

**Issue by rcrath** [theriex/membic#28]
MAnjaro linux, chrome, FIrefox, Vivaldi browsers
1. to replicate: login to membic.org
2. browse to community/themes.  themes appear.
3. click on a theme.  Crash here.
sent two emails with the crash output.  it crashed in three browsers: chrome, Firefox, and Vivaldi. maybe a linux thing?

**Comment by rcrath** [comment]
Interesting.  after I verified my email and logged back in it works fine.

**Comment by theriex** [comment]
I was fixing a bug in the theme retrieval code around the same time, which could be related.  That was from the RSS feed access, but it affected cache loading.  No log warnings today, but will poke around on this to see if I can get it to crash with a non-verified account.

**Comment by theriex** [comment]
Seems to be working now.  Chalking this up to corrupted cache from the RSS and my updates at the time. Thanks for reporting it.

**Comment by rcrath** [comment]
:)
